### ISSUE TITLE
bgzipped genome fasta

### ISSUE THREAD

**Issue by pkerpedjiev** [marbl/CHM13#16]
Just a suggestion, feel free to ignore and close this issue but it might be helpful to provide the gzipped fasta files (e.g. chm13.draft_v1.0.fasta.gz) as bgzipped files. This will make it possible to use with bioinformatics tools requiring random access to the files.

**Comment by skoren** [comment]
Sorry this completely dropped of our radar. There hasn't been too much demand for hosting the bzip versions so I'd prefer to avoid duplication and stick with the gz files. You could decompress before analysis or re-compress to bzip2 after downloading.
