### ISSUE TITLE
UCSC genome browser hub

### ISSUE THREAD

**Issue by gevro** [marbl/CHM13#18]
Is there a UCSC genome browser hub for CHM13-v1? That would make it easy to start doing easy liftovers, adding tracks, etc. Thanks.

**Comment by skoren** [comment]
Not yet but in the works, stay tuned

**Comment by ramoya** [comment]
will this hub also include a corresponding gene track?

**Comment by skoren** [comment]
Yes, both of these should be available by the end of this month

**Comment by skoren** [comment]
Available now
