### ISSUE TITLE
Centromere PFGE Southern blot valiation

### ISSUE THREAD

**Issue by zhoudreames** [marbl/CHM13#25]
in your article ,the centromere was valiated by PFGE Southern blotting.I asked you Which company did this experiment in? we want to do this experiment for my project in the future,thanks~

**Comment by zhoudreames** [comment]
@treangen @skoren @snurk @MihaiPop

**Comment by skoren** [comment]
Why do you tag people who are not even on the chrX paper? Your comment is visible without this, no need to immediately ping everyone forcefully, that is bad GitHub etiquette. 

The answer to your question is in the manuscript, specifically a direct quote from the author contributions: "B.A.S. performed PFGE Southern blotting array size analysis." I'm not aware of a company that does this, one of our collaborators performed this analysis. The details of the method are in the supplement.

**Comment by zhoudreames** [comment]
I am so sorry to disturb you,i am a little bit hurry. as sam time ,thanks for your reply
