### ISSUE TITLE
Hg38 lift over to v1. 1

### ISSUE THREAD

**Issue by psheth-twist** [marbl/CHM13#27]
Hello,

What is the recommended method to liftover hg38 panel targets bed to v1. 1? I see the chain file for v1. 0 to 1.1 but nothing for hg38. Look forward to trying!

Thanks

**Comment by skoren** [comment]
The UCSC browser linked from the README should have the information for you to liftover GRCh38 to v1.0 (GRCh38 LASTZ track) and then you can use the chain to lift v1.0 to v1.1. The v1.1 version is almost identical to v1.0, it just has the rDNA gaps filled in.

**Comment by zhoudreames** [comment]
> The UCSC browser linked from the README should have the information for you to liftover GRCh38 to v1.0 (GRCh38 LASTZ track) and then you can use the chain to lift v1.0 to v1.1. The v1.1 version is almost identical to v1.0, it just has the rDNA gaps filled in.

I want to gain chain information from my  assemblies ,how to get it ? thanks~
