### ISSUE TITLE
Is there a downloadable GTF/GFF file? 

### ISSUE THREAD

**Issue by apredeus** [marbl/CHM13#28]
Hello T2T team, 

Congratulations on the finished genome - this is an absolutely staggering achievement! 

Is there a link to the annotation used in the paper in GTF or GFF format? I've found the UCSC browser page, but the gene tracks there are very numerous and it's not clear how to download them. 

Thank you in advance!

**Comment by Chayonedesouza** [comment]
Great. !!

**Comment by skoren** [comment]
The track you want is the CAT Genes + Liftoff V4 (http://genome.ucsc.edu/cgi-bin/hgTrackUi?hgsid=1121067105_Pel2UYQAuyd8gnHxlMCsp3E4I5Jr&db=hub_2395475_t2t-chm13-v1.0&c=chr10&g=hub_2395475_consensus_CHM13_V4), you can download bigbed files through the browser. 

I added the gff files for both v1.0 and v1.1 to this page too for completeness.

**Comment by apredeus** [comment]
Thank you very much!

**Comment by wjyzidane** [comment]
Thanks for providing these files but I still can not find the download files

From this page : http://genome.ucsc.edu/cgi-bin/hgTrackUi?hgsid=1121067105_Pel2UYQAuyd8gnHxlMCsp3E4I5Jr&db=hub_2395475_t2t-chm13-v1.0&c=chr10&g=hub_2395475_consensus_CHM13_V4), it says "Data is downloadable from Globus in /team-genes/t2t-chm13-v1.0/CAT_V4/consensus_gene_set/"

But when I log in to the Globus and search this path. nothing is found:

![image](https://user-images.githubusercontent.com/34944811/122250407-a2b3ad80-ce97-11eb-95e9-cff05212a503.png)

Also, I wonder if the repeakMask for the v1.1 is also available for download? Thanks!

**Comment by skoren** [comment]
Ignore the globus link, that's internal to the T2T consortium. There are direct links to the GFF directly on the readme page:
https://github.com/marbl/CHM13#downloads. 

It is also available from the browser. If you click on the table schema link (http://genome.ucsc.edu/cgi-bin/hgTables?db=hub_2395475_t2t-chm13-v1.0&hgta_group=genes&hgta_track=hub_2395475_consensus_CHM13_V4&hgta_table=hub_2395475_consensus_CHM13_V4&hgta_doSchema=describe+table+schema), it will also give you the location of the backing data, namely: http://t2t.gi.ucsc.edu/chm13/hub/t2t-chm13-v1.0/CAT_V4/. You can see the gff file under the consensus_gene_set folder there.

**Comment by wjyzidane** [comment]
Thank you! This is very helpful.
