### ISSUE TITLE
chain file to liftover v1.1 to hg38

### ISSUE THREAD

**Issue by pushpinder11** [marbl/CHM13#29]
Is there a chain file available to perform a life over from v1.1 to hg38?

**Comment by skoren** [comment]
The UCSC browser provides chains between v1.0 and hg38 (http://genome.ucsc.edu/cgi-bin/hgTrackUi?hgsid=1128870359_RtudPntcUkokyX1DcrCMmfDWkfXd&db=hub_2395475_t2t-chm13-v1.0&c=chr10&g=hub_2395475_grch38Lastz). I also added links to them from this GitHub page. There are also chain files to liftover between v1.0 and v1.1. You should be able to do a two-step liftover (e.g. hg38->v1.0->v1.1) to go between hg38 and v1.1 using those.

**Comment by slw287r** [comment]
FYI: Chains between v1.1 and hg38
[http://t2t.gi.ucsc.edu/chm13/hub/t2t-chm13-v1.1/grch38PriLastz/](http://t2t.gi.ucsc.edu/chm13/hub/t2t-chm13-v1.1/grch38PriLastz/)

**Comment by bw2** [comment]
Thanks. 
I've added them to https://liftover.broadinstitute.org/

**Comment by lubertorubior** [comment]
Hello, thanks for sharing the chain files. Which should be the proper hg38 fasta file to use tools such as Picard's LiftoverVcf with these chain files?

Thanks.

**Comment by ebioman** [comment]
Hi
Thanks for the chain files, is there by chance anywhere described how they have been generated ?
Cheers
