### ISSUE TITLE
hg38 and chm13 1.1 liftovers?

### ISSUE THREAD

**Issue by mvelinder** [marbl/CHM13#34]
Are there chain files somewhere to go from:
hg38 > chm13 1.1
chm13 1.1 > hg38
?

The only way I saw to achieve this was to go from hg38 > chm13 1.0 > chm13 1.1. It'd be preferred to just go directly to 1.1

Thanks!

**Comment by skoren** [comment]
Unfortunately, at present no. You have to do the two-step liftover. The chain from 1.0 to 1.1 is quite simple (filling gaps) so, in my experience, it won't lose any of your features from v1.0. We should have an updated liftover once the UCSC browser is updated to 1.1 but until then you have to use both liftovers.

**Comment by mvelinder** [comment]
All good. Thanks @skoren ! I'll just do the two step liftover

**Comment by zhoudreames** [comment]
> Unfortunately, at present no. You have to do the two-step liftover. The chain from 1.0 to 1.1 is quite simple (filling gaps) so, in my experience, it won't lose any of your features from v1.0. We should have an updated liftover once the UCSC browser is updated to 1.1 but until then you have to use both liftovers.

how to liftover between assemblies? we want to gain chain information from my project，thanks~
