### ISSUE TITLE
BSGenome package

### ISSUE THREAD

**Issue by gevro** [marbl/CHM13#38]
Hi,
Is it possible to create a BSgenome package for CHM13 v1.0 and v1.1, which will make CHM13 accessible to many R packages?
Thanks.

**Comment by skoren** [comment]
I've never used BSgenome so I'm not familiar with it. It seems that it can build packages directly from UCSC 2bit files which are available from the UCSC browser links for either v1.0 or v1.1 (e.g.: http://t2t.gi.ucsc.edu/chm13/hub/t2t-chm13-v1.1/genome/). Does that give you want you need?

**Comment by gevro** [comment]
Thanks. Yes, I can build it manually from that.
