### ISSUE TITLE
how to draw coverage plots from your article "completehuman genome"

### ISSUE THREAD

**Issue by zhoudreames** [marbl/CHM13#42]
Hi,I am very happy to see your perfect aritcle had been preprinted,and we want to draw this coverage plot following your metnod  ,that showing you in blow.can you tell me how to draw it or do you provide me code ? Thanks~
![image](https://user-images.githubusercontent.com/54714639/147457090-f485b57d-b3e6-4f1a-b09f-ef0bd66d545b.png)

**Comment by arangrhie** [comment]
Hello @zhoudreames ,

Each tracks were loaded on [IGV](https://software.broadinstitute.org/software/igv/) from coverage .wig files and overlaid with Illustrator.
The .wig of the primary alignment was generated as written [here](https://github.com/arangrhie/T2T-Polish/tree/master/winnowmap), and marker assisted alignments following the steps from [here](https://github.com/arangrhie/T2T-Polish/tree/master/marker_assisted).

IGV settings could be found in [this xml](https://s3-us-west-2.amazonaws.com/human-pangenomics/T2T/CHM13/publications/Nurk_2021/fig3/v1.1_main_figure_3.xml).
Download it and try "Open Session".

Thanks,
Arang
