### ISSUE TITLE
Bionano Saphyr BNX and CMAP

### ISSUE THREAD

**Issue by erikhuck** [marbl/CHM13#44]
I have a few questions about these files
* Does the BNX file contain all the data necessary to create a truly complete Bionano optical genome mapping version of the CHM13 reference genome? Meaning will it contain telomere to telomere structural variant (SV) information (all the SVs in the genome from all the chromosomes)?
* Does the BNX file contain data from the Y chromosome as well?
* How was the cmap created? Was it created from the BNX file using bionano's software (bionano-solve or bionano access)? Can it be used as a reference for aligning other cmap files from samples processed using bionano's saphyr instrument?

**Comment by erikhuck** [comment]
Also I'd be happy to make a pull request with the answers to these questions included in the README for future researchers

**Comment by skoren** [comment]
- The BNX is the standard sequencing run of Bionano. I'm not sure what you mean by truly complete. There are regions of the genome w/o restriction sites and so would be missing. It is complete in the sense that it was sequenced from the whole genome.
 - The Y chromosome comes from HG002 so the CHM13 optical map would not contain a Y.
 - It was run through bionano-solve but it wasn't anchored to the T2T assembly. You can use it as a reference but, as I said above, it won't be T2T and will have breaks in the assembly. It would be similar to any other human genome sequenced by Bionano. I guess it would be possible to anchor the Bionano contigs onto the CHM13 T2T sequence but why not just use the T2T sequence itself as a reference for other cmap files?

Does that answer your questions?
