### ISSUE TITLE
GFF3 V1.1

### ISSUE THREAD

**Issue by erikhuck** [marbl/CHM13#46]
The annotations available here: https://s3-us-west-2.amazonaws.com/human-pangenomics/T2T/CHM13/assemblies/annotation/chm13.draft_v1.1.gene_annotation.v4.gff3.gz appear to be version 1.1 and do not contain Y chromosome data.

Is there a v2.0 GFF3 available with Y chromosome information?

**Comment by arangrhie** [comment]
We will post it when it becomes available.

**Comment by skoren** [comment]
Available now.
