### ISSUE TITLE
CHM13 cytoband positions for building an ideogram

### ISSUE THREAD

**Issue by mike-molnar** [marbl/CHM13#47]
Hello,

Thanks for all your great work in building the CHM13 assembly!  I would like to plot some of my results of v2.0 using karyoploteR, and I am able to build a custom ideogram, but I cannot find a file with the positions of the cytobands.  I see the centromere and telomere files for v1.1 on the UCSC table browser, but I was wondering if there is a BED file with all of the cytoband positions?

Thanks,
Mike

**Comment by mike-molnar** [comment]
Hi Mark,

Awesome!  Thanks for the quick reply. 

Mike

**Comment by hhuili** [comment]
> Hi Mike, I put the V2.0 cytoband BED here: http://t2t.gi.ucsc.edu/chm13/hub/t2t-chm13-v2.0/download/chm13v2.0_cytobands_allchrs.bed.gz Mark

Hi Diekhans,

The link is broken, can you provide it again?

Thanks a lot !
Huihui Li

**Comment by diekhans** [comment]
Apologies, the link broke as part of reorganizing around moving
to UCSC.  This link should work again:

http://t2t.gi.ucsc.edu/chm13/hub/t2t-chm13-v2.0/download/chm13v2.0_cytobands_allchrs.bed.gz
