### ISSUE TITLE
how to obtain chain information from any two assemblies(liftover)

### ISSUE THREAD

**Issue by zhoudreames** [marbl/CHM13#48]
I want to use my assembled genome to liftover reference genome, how to do it? thanks ~

**Comment by diekhans** [comment]
liftover files for V1.1 are in 
http://t2t.gi.ucsc.edu/chm13/hub/t2t-chm13-v1.1/downloads/

V2.0 is not available yet

**Comment by zhoudreames** [comment]
> liftover files for V1.1 are in http://t2t.gi.ucsc.edu/chm13/hub/t2t-chm13-v1.1/downloads/
> 
> V2.0 is not available yet

thanks for your reply, can I make the leftover files by myself? i want to obtain the chain files from my assembled genome. how to do it ?  thanks again~

**Comment by skoren** [comment]
This question doesn't seem specific/relevant to CHM13. Are you're just interested in how to build a new chain file? This wiki has some information: http://genomewiki.ucsc.edu/index.php/LiftOver_Howto and there's more guides if you just google for how to build chain files.
