### ISSUE TITLE
hg38 to CHM13 LiftOver and chr15 seg dup

### ISSUE THREAD

**Issue by mvelinder** [marbl/CHM13#49]
Hoping someone might be able to help in interpretation of a hg38 seg dup and how this sequence is represented in CHM13. We have two variants of interest at chr15:82229032 and chr15:82241415 (GRCh38) - both of which are within a known segmental duplication on chr15 (in GRCh38) https://genome.ucsc.edu/cgi-bin/hgc?hgsid=1302038497_dN3q1vp2PMvkQkstUHwVIwAzCuA3&db=hg38&c=chr15&l=82130232&r=82262734&o=82190662&t=82270742&g=genomicSuperDups&i=chr15%3A84066812 

We lifted these variants over using the `hg38.t2t-chm13-v1.0.over.chain.gz` chain to lift hg38 to CHM13 v1 and then the `v1.0_to_v1.1.chain` chain to lift CHM13 v1 to v1.1. Interestingly, with this approach, both coordinates lift over to the same position in CHM13v1.1 at chr15:80105532. One interpretation we considered was that the two seg dups in GRCh38 have been consolidated/collapsed into one in CHM13v1.1. Is that the correct interpretation? Could you confirm that chr15:80105532 (CHM13v1.1) is the correct liftover coordinate for **both** chr15:82229032 and chr15:82241415 (GRCh38) positions?

Additionally, when aligning our reads to CHM13v1.1 we don't see evidence for the chr15:82241415 (GRCh38) variant (at the same position, according to liftover). We interpreted this as the variant-supporting reads being (properly?) aligned to a different region of the CHM13v1.1 reference, instead of being (improperly?) aligned to the chr15:82241415 region where they supported a variant call. Would you say that's the correct interpretation?

Any insights here would be greatly appreciated! Thanks so much!

**Comment by arangrhie** [comment]
Hello @mvelinder, try the curated chain file [grch38-chm13v2.chain](https://s3-us-west-2.amazonaws.com/human-pangenomics/T2T/CHM13/assemblies/chain/v1_nflo/grch38-chm13v2.chain) and see if this is still lifting over to the same locus. Using the new chain file, the coordinates now map to chr15:80093147 and chr15:80105532.
Note chm13v1.1 only differs on chrY for chm13v2.0. More details for the chain files are available in the updated README [download](https://github.com/marbl/CHM13#downloads).
