### ISSUE TITLE
An unmasked version of the genome?

### ISSUE THREAD

**Issue by YiyanYang0728** [marbl/CHM13#55]
Hello CHM13 staff, 

Thank you for providing such a high-quality genome!
May I have an unmasked version of the genome? I would like to see some repeats masked in this genome. Thank you for your help.

Best wishes,
Yiyan

**Comment by skoren** [comment]
All the masking is soft-masked so the repeats would be present, just in lower case. Which sequence could you not access?

**Comment by YiyanYang0728** [comment]
Awesome! Thank you for your reply and sorry for the misunderstanding. I can close the case now.

**Comment by arangrhie** [comment]
To clarify, it is only the PAR that has been hard-masked on the Y in the "maskedY" fasta. The rest are soft-masked.

**Comment by ValZapod** [comment]
> is only the PAR that has been hard-masked

PAR1 or PAR2? Or both?
