### ISSUE TITLE
GFF input file used for generating CAT and Liftoff CHM13.v2.0.gff3 annotation

### ISSUE THREAD

**Issue by bernardo-heberle** [marbl/CHM13#57]
Hi,

Can you tell me the input GFF annotation file that was used for generating CAT and Liftoff [CHM13.v2.0.gff3](http://courtyard.gi.ucsc.edu/~mhauknes/T2T/t2t_Y/annotation_set/CHM13.v2.0.gff3) annotation? If possible could you also provide the specific release of the annotation that was used?

**Comment by arangrhie** [comment]
Hello @bernardo-heberle,

It is GENCODE v35, annotation was generated the same way as CHM13v1.0 as described in Nurk et al. Science paper. A few more iso-seq data was used for annotating the Y, obtained from HG002. We are in preparation for a paper describing more details about the Y and the resources, but do let us know if you have more questions!

**Comment by bernardo-heberle** [comment]
Thank you, @arangrhie, for the super fast and helpful reply!
