### ISSUE TITLE
More info on the centromeric satellite masking BED file

### ISSUE THREAD

**Issue by guilhermesena1** [marbl/CHM13#68]
Hello,

Thank you very much for all the effort in this historic project!

We have some sequencing data which requires a particularly complex analysis in centromeric regions. We are using the [centromeric satellite masked BED file](https://s3-us-west-2.amazonaws.com/human-pangenomics/T2T/CHM13/assemblies/annotation/chm13.draft_v2.0.cen_mask.bed), but we could not find too much information regarding how these regions were inferred. Is it based on sequence patterns? Staining? Exactly how were the boundaries defined?

We would be extremely grateful if any references on the construction of these regions could be provided. Thank you!

**Comment by arangrhie** [comment]
Hello,

Please use the [complete cen/sat annotation](https://s3-us-west-2.amazonaws.com/human-pangenomics/T2T/CHM13/assemblies/annotation/chm13v2.0_censat_v2.0.bed). The hor (alpha HOR), dhor (diverged alpha) and mon (monomers) may be the ones you would be interested to look at for the centromeric annotation.

Detailed methods on how the cen/sats were defined is described in [Altemose et al](https://doi.org/10.1126/science.abl4178).

Best,
Arang

**Comment by guilhermesena1** [comment]
Thank you so much for the quick response! This definitely addresses our question.

**Comment by Marynotmartha** [comment]
I just don’t get why I don’t get answers. It’s my dna.
