### ISSUE TITLE
methylation tables

### ISSUE THREAD

**Issue by ShuaiNIEgithub** [marbl/CHM13#69]
Hi, T2T team

I am doing research on methylation. I appreciate that the article gives a detailed pipeline to identify CpG methylation in T2T-CHM13 using long-read nanopore data. However the huge amount of calculations is still a challenge for me. So could you please share the methylation tables (in BED or bedGraph formats) to me, it would be a great help.

Tons of thanks.
Jeffery

**Comment by arangrhie** [comment]
Hello, the methylation data for CHM13 can be found here: https://s3-us-west-2.amazonaws.com/human-pangenomics/index.html?prefix=T2T/CHM13/assemblies/annotation/regulation/
The .bw file contains the methylation profile in big wiggle, called with Nanopolish v13 using loglik cutoffs of -1.5 and 1.5.
The CGI contains CpG Islands generated with the EMBOSS v6.6.0.0 software. Parameters to determine a CpG island were window size 100bp, minimum length of 200bp, minimum observered/expected ratio of .6 and a minimum CG percentage of 50%.

Creditting Ariel Gershman who generated these tracks.

Best,
Arang

**Comment by ShuaiNIEgithub** [comment]
Thank you so much!
