### ISSUE TITLE
partition233-234.tgz md5 

### ISSUE THREAD

**Issue by SarahChen0401** [marbl/CHM13#70]
partition233-234.tgz has been downloaded three times. and its md5 always be a78f496e2c086dccdb7f62db866c1525 which is not consistent with original md5.  what's the problem?

**Comment by skoren** [comment]
I downloaded the file and confirm the md5sum didn't match what's on the page. I re-compressed the data and compared to the downloaded file and they are identical so I think this is a typo on the README and not a corruption of the file. I corrected the MD5 on the README to match what you reported and what I got on our system (a78f496e2c086dccdb7f62db866c1525). I also downloaded a subset of partitions 232 through 243 and confirmed they all match the MD5s on the README. Please let us know if you find any other discrepancy in the data.
