### ISSUE TITLE
CHM13 v2 genome accessibility masks for 1000 Genomes data

### ISSUE THREAD

**Issue by zhang919** [marbl/CHM13#72]
Hi, 
I noted you published a data on [1000 Genomes Project](https://s3-us-west-2.amazonaws.com/human-pangenomics/index.html?prefix=T2T/CHM13/assemblies/variants/1000_Genomes_Project/chm13v2.0/), recalled on T2T-CHM13v2.0  available for all chromosomes, for the entire 3,202 samples or the unrelated 2504 samples. 

As classic 1000g release they  have a genome accessibility masks (for example: http://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/supporting/accessible_genome_masks/), Is here has same resources available for CHM13 v2.0?

Regards

**Comment by arangrhie** [comment]
Hi @zhang919 ,

We have generated the accessibility mask tracks for short-reads [here](https://s3-us-west-2.amazonaws.com/human-pangenomics/index.html?prefix=T2T/CHM13/assemblies/annotation/accessibility/) (Crediting Dylan Taylor and Rajiv McCoy).
We are in the process of uploading them to UCSC genome browser. Until then, please use the `combined_mask.bed.gz`.

Best,
Arang
