### ISSUE TITLE
SF3B3 gene annotation missing in gff3

### ISSUE THREAD

**Issue by fbrundu** [marbl/CHM13#74]
I am interested on the SF3B3 gene, and I was able to find the entry in the gff3 file for hg38 (e.g., [gencode 43](https://www.gencodegenes.org/human/release_43.html)):

```
chr16	HAVANA	gene	70523791	70577670	.	+	.	ID=ENSG00000189091.13;gene_id=ENSG00000189091.13;gene_type=protein_coding;gene_name=SF3B3;level=1;hgnc_id=HGNC:10770;tag=ncRNA_host;havana_gene=OTTHUMG00000137582.8
```

However, I cannot find the entry with type "gene" (on third column) for such gene in the gff3 posted on this repository. Other annotations for this gene, e.g., "transcript", are available:

```
CDS
exon
intron
start_codon
stop_codon
transcript
```

What could be the reason for this, and would there be a work-around to this issue?

**Comment by diekhans** [comment]
It is unclear why a gene record did not get written for this.  An issue was created for CAT, however,
the software is between maintainers.  You could generate the gene records yourself.  Also, Ensembl, has chm13 annotations in their HPRC release.  NCBI has also released CHM13 annotations

https://github.com/ComparativeGenomicsToolkit/Comparative-Annotation-Toolkit/issues/286

**Comment by ValZapod** [comment]
Why not just take or at least compare with https://www.ncbi.nlm.nih.gov/gene/23450? It has GRCh37.p13, and two current GRCh38.p14 and T2T-CHM13v2.0.

**Comment by arangrhie** [comment]
Hello, just to add on this.

SF3B3 is found in the [curated RefSeq/Liftoff annotation](https://s3-us-west-2.amazonaws.com/human-pangenomics/T2T/CHM13/assemblies/annotation/chm13v2.0_RefSeq_Liftoff_v5.1.gff3.gz) as following:
```
chr16   Liftoff gene    76334997        76388857        .       +       .       ID=SF3B3;gene_name=SF3B3;db_xref=MIM:605592;description=splicing factor 3b subunit 3;gbkey=Gene;gene=SF3B3;gene_biotype=protein_coding;gene_synonym=STAF130;coverage=1.0;sequence_ID=1.0;valid_ORFs=1;extra_copy_number=0;copy_num_ID=SF3B3_0
```
