### ISSUE TITLE
Is there phased 1000g variations data available base on CHM13 

### ISSUE THREAD

**Issue by zhangjy859** [marbl/CHM13#77]
Hi, 
I noted  Aganezov et. al. published a 1000 Genomes Project data with CHM13, is there phased 1000g variations data available?

Regrads

Zhang

**Comment by asylvz** [comment]
Hello, related to the issue. I guess you mean these VCFs (https://s3-us-west-2.amazonaws.com/human-pangenomics/index.html?prefix=T2T/CHM13/assemblies/variants/1000_Genomes_Project/chm13v2.0/all_samples_3202/)
Do they also include SVs? And is there a smaller version of the VCFs in terms of size, maybe with less info?

Thank you,
Arda
