### ISSUE TITLE
GENCODE gene annotation link is stale.

### ISSUE THREAD

**Issue by pwh124** [marbl/CHM13#79]
Hello,

The link to the GENCODE annotation leads to nowhere:
https://ftp.ensembl.org/pub/rapid-release/species/Homo_sapiens/GCA_009914755.4/geneset/2022_07/Homo_sapiens-GCA_009914755.4-2022_07-genes.gff3.gz

**Comment by diekhans** [comment]
this should be 
https://ftp.ensembl.org/pub/rapid-release/species/Homo_sapiens/GCA_009914755.4/ensembl/geneset/2022_07/Homo_sapiens-GCA_009914755.4-2022_07-genes.gff3.gz
