### ISSUE TITLE
Length of chm13v2.0

### ISSUE THREAD

**Issue by pholur** [marbl/CHM13#87]
--- newbie ---
On the README here (https://github.com/marbl/CHM13/), this link  [chm13v2.0.fa.gz](https://s3-us-west-2.amazonaws.com/human-pangenomics/T2T/CHM13/assemblies/analysis_set/chm13v2.0.fa.gz) contains only ~3B characters. I read online that the total genome should be of length ~6B? Could someone tell me what I am missing?
`>> wc -m chm13v2.0.fa` returns 3B.
Thanks a ton!

**Comment by skoren** [comment]
No, the genome should be approximately 3gb. 6gb would be the size of a diploid human genome for both haplotypes but CHM13 is haploid (well technically diploid but the haplotypes are identical in most cases) so there's only one haplotype to represent.

**Comment by pholur** [comment]
Thanks a ton!
