### ISSUE TITLE
m64062_190807_194840 subreads

### ISSUE THREAD

**Issue by romaingroux** [marbl/CHM13#91]
Hi, 

I would like to congratulate you all for this amazing work of assembling and sharing this data publicly.

Recently I downloaded the raw subreads data (in bam format) as indicated in https://github.com/marbl/CHM13/blob/master/Sequencing_data.md

However, I noticed there are 4 corresponding CCS files available from the SRA (https://www.ncbi.nlm.nih.gov/sra/?term=SRX789768*+CHM13). Based on this, it seems that the subreads for movie m64062_190807_194840 (corresponding to SRR11292122) are nowhere to be found. 

I was wondering if I could get directed to the corresponding data in bam format?

Thank you

**Comment by skoren** [comment]
Unfortunately, the raw subreads was not saved from the instrument for this cell. There was a period of time when subreads were not saved off the instrument so unfortunately the only thing available for this cell is the CCS reads.

**Comment by romaingroux** [comment]
Oups... 
Thank you very much for this quick answer
