### ISSUE TITLE
help for 70x PacBio CLR data

### ISSUE THREAD

**Issue by lixingqiancs** [marbl/CHM13#93]
Hi.

I want to download Chm13 70x PacBio CLR data. But I only found HiFi data.

Could you give me more information?

**Comment by skoren** [comment]
The CLR data was previously generated so it was already publicly available. It is listed on the data availability page, specifically: https://github.com/marbl/CHM13/blob/master/Sequencing_data.md#previously-generated-pacbio-data. You can view the SRA data and filter by genomic + PacBio to get the data. For example, this is one of the CLR runs: https://trace.ncbi.nlm.nih.gov/Traces/?view=run_browser&acc=SRR2026890&display=metadata
