### ISSUE TITLE
about naming difference in the same database file 

### ISSUE THREAD

**Issue by zincuum** [marbl/CHM13#97]
Dear T2T-CHM13 Teams 

Thank you for making this amazing set of resources available.
I have a question about the naming convention for the files you provide.
If you go to the download section of T2T github, there are files related to vcf calls.
Here, ClinVar20220313, which liftover the GRCh38 file, is on the main screen, and if you download it, it is the same as **chm13v2.0_ClinVar20220313.vcf.**
And when you enter FTP, there is another T2T-CHM13 Clinvar file, **Homo_sapiens-GCA_009914755.4-2022_10-clinvar.vcf.**
I want to know the difference between these two files.
1. First of all, I am curious as to when it is named chm13 and when it is named GCA_009914755.4.
2. I am curious about the difference in terms of content between these two files.

**Comment by arangrhie** [comment]
Hi @zincuum,

Sorry, I am confused - which FTP are you referring to?
GCA_009914755.4 is the GenBank accession for the submitted assembly.

**Comment by zincuum** [comment]
> Hi @zincuum,
> 
> Sorry, I am confused - which FTP are you referring to? GCA_009914755.4 is the GenBank accession for the submitted assembly.

In the attached captured photo, I am talking about the dragged FTP. The link for this is as follows: https://ftp.ensembl.org/pub/rapid-release/species/Homo_sapiens/GCA_009914755.4/ensembl/variation/2022_10/vcf/
<img width="638" alt="FTP_snpshot" src="https://github.com/marbl/CHM13/assets/124128112/b988fb63-72c2-47b4-8262-6449663682a2">

**Comment by arangrhie** [comment]
I believe the data in that Ensembl FTP were created from the GRCh38-based HAL file, downloaded from the Minigraph-Cactus alignment of [Liao et al. 2022 (Liao et al. 2022)](https://github.com/human-pangenomics/hpp_pangenome_resources/blob/main/hprc-v1.0-mc.md).
The rest of the 'lifted' data listed in this github were generated with using a curated chain file between GRCh38 and CHM13 alignments.

**Comment by zincuum** [comment]
What you mean is that both files are created by lifting over GRCH38, but the difference is that Ensembl FTP uses a grch38 file created by Minigraph-Cactus alignment as input, while the one on github uses a grch38 file curated by NCBI?
