### ISSUE TITLE
CLR reads

### ISSUE THREAD

**Issue by YanChunL** [marbl/CHM13#98]
I am sorry to bother you, first of all，thank you for making this amazing set of resources available.Now,I want to ues the CHM13 64x PacBio CLR reads。I want to know if I should download both of the following data sets and merge them together, or if I should just download one
![$2WWPKCZR OHT8_IM_PAJYB](https://github.com/marbl/CHM13/assets/162942182/79b47299-3a2b-4e65-ac98-3ba150dd0f7c)

**Comment by skoren** [comment]
I'd say it depends what you're trying to do. They're both from CHM13 so you can download all the RS data if you want higher coverage). We didn't use either of these for the recent T2T assemblies (v0.8 on) and used a subset (listed here: https://raw.githubusercontent.com/nanopore-wgs-consortium/CHM13/master/pbP6Cells) for the older assembly polishing.

**Comment by YanChunL** [comment]
Thank you for your response. I wish you and your team all the best.

**Comment by YanChunL** [comment]
Thank you for your response. I wish you and your team all the best.
